/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface UniInterface extends ethers.utils.Interface {
  functions: {
    "deployed()": FunctionFragment;
    "deposit(uint256)": FunctionFragment;
    "depositTimestamps(address,uint256)": FunctionFragment;
    "maxTotalUSDC()": FunctionFragment;
    "maxTotalWETH()": FunctionFragment;
    "minLockDuration()": FunctionFragment;
    "nonfungiblePositionManager()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setMaxTotalUSDC(uint256)": FunctionFragment;
    "setMaxTotalWETH(uint256)": FunctionFragment;
    "setMinLockDuration(uint256)": FunctionFragment;
    "setWeeklyReward(uint256)": FunctionFragment;
    "totalLiquidityUSDC()": FunctionFragment;
    "totalLiquidityWETH()": FunctionFragment;
    "totalsUSDC(uint256)": FunctionFragment;
    "totalsWETH(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "weeklyReward()": FunctionFragment;
    "weth()": FunctionFragment;
    "withdrawToken(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "deployed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTimestamps",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxTotalUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTotalWETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minLockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nonfungiblePositionManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTotalUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTotalWETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinLockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWeeklyReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLiquidityUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLiquidityWETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalsUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalsWETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyReward",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deployed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minLockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nonfungiblePositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTotalUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTotalWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinLockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWeeklyReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidityUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidityWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalsUSDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalsWETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weeklyReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;

  events: {
    "Deposit(uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SetMaxTotalUSDC(uint256)": EventFragment;
    "SetMaxTotalWETH(uint256)": EventFragment;
    "SetMinLockDuration(uint256)": EventFragment;
    "SetWeeklyReward(uint256)": EventFragment;
    "Withdrawal(uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxTotalUSDC"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxTotalWETH"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMinLockDuration"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetWeeklyReward"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawal"): EventFragment;
}

export type DepositEvent = TypedEvent<
  [BigNumber, string] & { tokenId: BigNumber; owner: string }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type SetMaxTotalUSDCEvent = TypedEvent<
  [BigNumber] & { maxTotal: BigNumber }
>;

export type SetMaxTotalWETHEvent = TypedEvent<
  [BigNumber] & { maxTotal: BigNumber }
>;

export type SetMinLockDurationEvent = TypedEvent<
  [BigNumber] & { duration: BigNumber }
>;

export type SetWeeklyRewardEvent = TypedEvent<
  [BigNumber] & { reward: BigNumber }
>;

export type WithdrawalEvent = TypedEvent<
  [BigNumber, string, BigNumber] & {
    tokenId: BigNumber;
    owner: string;
    rewardPaid: BigNumber;
  }
>;

export class Uni extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UniInterface;

  functions: {
    deployed(overrides?: CallOverrides): Promise<[BigNumber]>;

    deposit(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositTimestamps(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxTotalUSDC(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxTotalWETH(overrides?: CallOverrides): Promise<[BigNumber]>;

    minLockDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxTotalUSDC(
      _newMaxTotalUSDC: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxTotalWETH(
      _newMaxTotalWETH: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinLockDuration(
      _newMinLockDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWeeklyReward(
      _newReward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalLiquidityUSDC(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalLiquidityWETH(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalsUSDC(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalsWETH(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    weeklyReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    weth(overrides?: CallOverrides): Promise<[string]>;

    withdrawToken(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deposit(
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositTimestamps(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxTotalUSDC(overrides?: CallOverrides): Promise<BigNumber>;

  maxTotalWETH(overrides?: CallOverrides): Promise<BigNumber>;

  minLockDuration(overrides?: CallOverrides): Promise<BigNumber>;

  nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxTotalUSDC(
    _newMaxTotalUSDC: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxTotalWETH(
    _newMaxTotalWETH: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinLockDuration(
    _newMinLockDuration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWeeklyReward(
    _newReward: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalLiquidityUSDC(overrides?: CallOverrides): Promise<BigNumber>;

  totalLiquidityWETH(overrides?: CallOverrides): Promise<BigNumber>;

  totalsUSDC(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  totalsWETH(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  weeklyReward(overrides?: CallOverrides): Promise<BigNumber>;

  weth(overrides?: CallOverrides): Promise<string>;

  withdrawToken(
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployed(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    depositTimestamps(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxTotalUSDC(overrides?: CallOverrides): Promise<BigNumber>;

    maxTotalWETH(overrides?: CallOverrides): Promise<BigNumber>;

    minLockDuration(overrides?: CallOverrides): Promise<BigNumber>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setMaxTotalUSDC(
      _newMaxTotalUSDC: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxTotalWETH(
      _newMaxTotalWETH: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinLockDuration(
      _newMinLockDuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setWeeklyReward(
      _newReward: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    totalLiquidityUSDC(overrides?: CallOverrides): Promise<BigNumber>;

    totalLiquidityWETH(overrides?: CallOverrides): Promise<BigNumber>;

    totalsUSDC(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalsWETH(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    weeklyReward(overrides?: CallOverrides): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<string>;

    withdrawToken(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Deposit(uint256,address)"(
      tokenId?: null,
      owner?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { tokenId: BigNumber; owner: string }
    >;

    Deposit(
      tokenId?: null,
      owner?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { tokenId: BigNumber; owner: string }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "SetMaxTotalUSDC(uint256)"(
      maxTotal?: null
    ): TypedEventFilter<[BigNumber], { maxTotal: BigNumber }>;

    SetMaxTotalUSDC(
      maxTotal?: null
    ): TypedEventFilter<[BigNumber], { maxTotal: BigNumber }>;

    "SetMaxTotalWETH(uint256)"(
      maxTotal?: null
    ): TypedEventFilter<[BigNumber], { maxTotal: BigNumber }>;

    SetMaxTotalWETH(
      maxTotal?: null
    ): TypedEventFilter<[BigNumber], { maxTotal: BigNumber }>;

    "SetMinLockDuration(uint256)"(
      duration?: null
    ): TypedEventFilter<[BigNumber], { duration: BigNumber }>;

    SetMinLockDuration(
      duration?: null
    ): TypedEventFilter<[BigNumber], { duration: BigNumber }>;

    "SetWeeklyReward(uint256)"(
      reward?: null
    ): TypedEventFilter<[BigNumber], { reward: BigNumber }>;

    SetWeeklyReward(
      reward?: null
    ): TypedEventFilter<[BigNumber], { reward: BigNumber }>;

    "Withdrawal(uint256,address,uint256)"(
      tokenId?: null,
      owner?: null,
      rewardPaid?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { tokenId: BigNumber; owner: string; rewardPaid: BigNumber }
    >;

    Withdrawal(
      tokenId?: null,
      owner?: null,
      rewardPaid?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { tokenId: BigNumber; owner: string; rewardPaid: BigNumber }
    >;
  };

  estimateGas: {
    deployed(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositTimestamps(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxTotalUSDC(overrides?: CallOverrides): Promise<BigNumber>;

    maxTotalWETH(overrides?: CallOverrides): Promise<BigNumber>;

    minLockDuration(overrides?: CallOverrides): Promise<BigNumber>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxTotalUSDC(
      _newMaxTotalUSDC: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxTotalWETH(
      _newMaxTotalWETH: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinLockDuration(
      _newMinLockDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWeeklyReward(
      _newReward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalLiquidityUSDC(overrides?: CallOverrides): Promise<BigNumber>;

    totalLiquidityWETH(overrides?: CallOverrides): Promise<BigNumber>;

    totalsUSDC(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalsWETH(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    weeklyReward(overrides?: CallOverrides): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawToken(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositTimestamps(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxTotalUSDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxTotalWETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minLockDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonfungiblePositionManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxTotalUSDC(
      _newMaxTotalUSDC: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxTotalWETH(
      _newMaxTotalWETH: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinLockDuration(
      _newMinLockDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWeeklyReward(
      _newReward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalLiquidityUSDC(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalLiquidityWETH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalsUSDC(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalsWETH(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    weeklyReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawToken(
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
