// This file was generated by script

import arrowDown from './arrow-down.svg';
import book from './book.svg';
import btnBg from './btn-bg.svg';
import compositeBtnL1 from './composite-btn-l1.svg';
import compositeBtnL2 from './composite-btn-l2.svg';
import compositeBtnL3 from './composite-btn-l3.svg';
import email from './email.svg';
import github from './github.svg';
import information from './information.svg';
import linkHover1 from './link-hover-1.svg';
import linkHover2 from './link-hover-2.svg';
import linkHover3 from './link-hover-3.svg';
import medium from './medium.svg';
import musicWave from './music-wave.svg';
import twitter from './twitter.svg';
import youtube from './youtube.svg';

const icons = {
  'arrow-down': arrowDown,
  book,
  'btn-bg': btnBg,
  'composite-btn-l1': compositeBtnL1,
  'composite-btn-l2': compositeBtnL2,
  'composite-btn-l3': compositeBtnL3,
  email,
  github,
  information,
  'link-hover-1': linkHover1,
  'link-hover-2': linkHover2,
  'link-hover-3': linkHover3,
  medium,
  'music-wave': musicWave,
  twitter,
  youtube,
};

export default icons;
